---
- name: Copy pub key file to remote hosts from local tmp directory
  copy: src={{ local_tmp_keygen_file }} dest={{ dest_tmp_keygen_file }}

- name: Cat public key into variable
  shell: cat {{ dest_tmp_keygen_file }}
  register: pub_key

- name: Add public key to authorizated keys
  lineinfile: dest=~/.ssh/authorized_keys line="{{ pub_key['stdout_lines'][0] }}" state=present

- name: Delete temp file on remote
  file: path={{ dest_tmp_keygen_file }} state=absent
