#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - TEST_TYPE=default
    - DOCKER_CACHE=~/docker-cache
    - DOCKER_METRON_CENTOS=$DOCKER_CACHE/metron_centos.tar.gz
    - E2E_COMPOSE_HOME=metron-contrib/metron-docker-e2e/compose
    - DOCKER_COMPOSE_VERSION=1.8.0

install: true
language: java
jdk:
  - oraclejdk8
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - unzip -qq apache-maven-3.3.9-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
  - npm config set cache $HOME/.npm-cache --global
  - npm config set prefix $HOME/.npm-prefix --global
  - if [ -f ${DOCKER_METRON_CENTOS} ]; then gunzip -c ${DOCKER_METRON_CENTOS} | docker load; else docker build metron-contrib/metron-docker-e2e/compose/metron-centos/ -t "metron-centos"; fi

install:
  - time mvn -q -T 2C -DskipTests clean install
  - cd $E2E_COMPOSE_HOME && docker-compose up -d
  - if [ ! -f ${DOCKER_METRON_CENTOS} ]; then docker save metron-centos | gzip > ${DOCKER_METRON_CENTOS}; fi
  - cd $TRAVIS_BUILD_DIR

script:
   - ls -la
   - metron-contrib/metron-docker-e2e/scripts/wait_for_rest.sh localhost 8082
   - cd $E2E_COMPOSE_HOME && docker-compose logs metron-rest && cd ../../../
#   - mvn -q -T 2C surefire:test@unit-tests
#   - mvn -q surefire:test@integration-tests
#   - mvn -q test --projects metron-interface/metron-config
   - mvn test -Pe2e --projects=metron-interface/metron-alerts
#   - build_utils/verify_licenses.sh

before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/metron

cache:
  timeout: 1000
  directories:
  - $HOME/.npm-cache
  - $HOME/.npm-prefix
  - metron-interface/metron-config/node_modules
  - $HOME/.m2
  - $HOME/.npm
  - $DOCKER_CACHE
