install: true
language: java
jdk:
  - oraclejdk8
script:
  - |
    mvn -q -DskipTests -T 2C install && mvn -q -T 2C test && mvn -q -Dtest=\*IntegrationTest -DfailIfNoTests=false integration-test && build_utils/verify_licenses.sh
cache:
  directories:
  - $HOME/.m2
