language: java


jdk:
  - oraclejdk8
  - openjdk7
script:
  - |
    mvn apache-rat:check
    cd metron-streaming
    mvn -q integration-test package | grep -v "DEBUG\|INFO\|WARN"
    
after_success:
  bash <(curl -s https://codecov.io/bash)
