sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk7
  - oraclejdk8
install:
  - |
    cd metron-streaming
    mvn install -DskipTests=true
before_script:
  - pip install --user codecov
script:
  - |
    cd metron-streaming
    mvn test
after_success:
  - codecov
notifications:
  email: false
