install: true
language: java
jdk:
  - oraclejdk8
script:
  - |
    mvn apache-rat:check && mvn -q -T 2C test && mvn -q surefire:test@integration-tests && build_utils/verify_licenses.sh
cache:
  directories:
  - $HOME/.m2
