language: java

before_script:
  - pip install --user codecov
  
jdk:
  - oraclejdk8
  - openjdk7
script:
  - |
    mvn apache-rat:check
    cd metron-streaming
    mvn -q integration-test package | grep -v "DEBUG\|INFO\|WARN"
    
after_success:
  - codecov
