#
# install the `pcap-replay` initd service which will auto-magically begin
# replay pcap data when the service is started
#
---
- name: Create pcap directory
  file: path={{ pcap_replay_path }} state=directory mode=0755

- name: Install init.d service script
  copy: src=pcap-replay dest=/etc/init.d/pcap-replay

- name: Set permissions on service script
  file: path=/etc/init.d/pcap-replay mode=0755

- name: Install example pcap file
  copy: src=example.pcap dest={{ pcap_replay_path }}/
