#
# installs `tcpreplay` which is used to replay persisted pcap files stored
# in libpcap format
#
---
- name: Install prerequisites
  yum: name={{ item }}
  with_items:
    - "@Development tools"
    - libpcap
    - libpcap-devel

- name: Download tcpreplay
  get_url:
    url: "https://github.com/appneta/tcpreplay/releases/download/v{{ tcpreplay_version }}/tcpreplay-{{ tcpreplay_version }}.tar.gz"
    dest: "/tmp/tcpreplay-{{ tcpreplay_version }}.tar.gz"

- name: Extract tcpreplay tarball
  unarchive:
    src: "/tmp/tcpreplay-{{ tcpreplay_version }}.tar.gz"
    dest: /opt
    copy: no
    creates: "/opt/tcpreplay-{{ tcpreplay_version }}"

- name: Compile and install tcpreplay
  shell: "{{ item }}"
  args:
    chdir: "/opt/tcpreplay-{{ tcpreplay_version }}"
    creates: /usr/local/bin/tcpreplay
  with_items:
    - ./configure
    - make
    - make install
