name: "paloalto-local"
config:
    topology.workers: 1

components:
    -   id: "paloAltoParser"
        className: "com.opensoc.parsing.parsers.BasicPaloAltoFirewallParser"
    -   id: "genericMessageFilter"
        className: "com.opensoc.filters.GenericMessageFilter"
    -   id: "filenameFormat"
        className: "org.apache.storm.hdfs.bolt.format.DefaultFileNameFormat"
        configMethods:
            -   name: "withPath"
                args:
                    - "${bolt.hdfs.wip.file.path}"
    -   id: "messageField"
        className: "backtype.storm.tuple.Fields"
        constructorArgs:
            - ["message"]
    -   id: "recordFormat"
        className: "org.apache.storm.hdfs.bolt.format.DelimitedRecordFormat"
        configMethods:
            -   name: "withFieldDelimiter"
                args:
                    - "${bolt.hdfs.field.delimiter}"
            -   name: "withFields"
                args:
                    - ref: "messageField"
    -   id: "rotationPolicy"
        className: "org.apache.storm.hdfs.bolt.rotation.FileSizeRotationPolicy"
        constructorArgs:
            - ${bolt.hdfs.file.rotation.size.in.mb}
            - MB
    -   id: "syncPolicy"
        className: "org.apache.storm.hdfs.bolt.sync.CountSyncPolicy"
        constructorArgs:
            - ${bolt.hdfs.batch.size}
    -   id: "moveFileAction"
        className: "org.apache.storm.hdfs.common.rotation.MoveFileAction"
        configMethods:
            -   name: "toDestination"
                args:
                    - "${bolt.hdfs.finished.file.path}"
    -   id: "metricConfig"
        className: "org.apache.commons.configuration.BaseConfiguration"
        configMethods:
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.reporter.graphite"
                    - "${com.opensoc.metrics.reporter.graphite}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.reporter.console"
                    - "${com.opensoc.metrics.reporter.console}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.reporter.jmx"
                    - "${com.opensoc.metrics.reporter.jmx}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.graphite.address"
                    - "${com.opensoc.metrics.graphite.address}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.graphite.port"
                    - "${com.opensoc.metrics.graphite.port}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.TelemetryParserBolt.acks"
                    - "${com.opensoc.metrics.TelemetryParserBolt.acks}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.TelemetryParserBolt.emits"
                    - "${com.opensoc.metrics.TelemetryParserBolt.emits}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.TelemetryParserBolt.fails"
                    - "${com.opensoc.metrics.TelemetryParserBolt.fails}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.GenericEnrichmentBolt.acks"
                    - "${com.opensoc.metrics.GenericEnrichmentBolt.acks}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.GenericEnrichmentBolt.emits"
                    - "${com.opensoc.metrics.GenericEnrichmentBolt.emits}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.GenericEnrichmentBolt.fails"
                    - "${com.opensoc.metrics.GenericEnrichmentBolt.fails}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.TelemetryIndexingBolt.acks"
                    - "${com.opensoc.metrics.TelemetryIndexingBolt.acks}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.TelemetryIndexingBolt.emits"
                    - "${com.opensoc.metrics.TelemetryIndexingBolt.emits}"
            -   name: "setProperty"
                args:
                    - "com.opensoc.metrics.TelemetryIndexingBolt.fails"
                    - "${com.opensoc.metrics.TelemetryIndexingBolt.fails}"

spouts:
    -   id: "testingSpout"
        className: "com.opensoc.test.spouts.GenericInternalTestSpout"
        parallelism: 1
        configMethods:
            -   name: "withFilename"
                args:
                    - "SampleInput/PaloaltoOutput"
            -   name: "withRepeating"
                args:
                    - true

bolts:
    -   id: "parserBolt"
        className: "com.opensoc.parsing.TelemetryParserBolt"
        configMethods:
            -   name: "withMessageParser"
                args:
                    - ref: "paloAltoParser"
            -   name: "withOutputFieldName"
                args:
                    - "paloalto"
            -   name: "withMessageFilter"
                args:
                    - ref: "genericMessageFilter"
            -   name: "withMetricConfig"
                args:
                    - ref: "metricConfig"
    -   id: "hdfsBolt"
        className: "org.apache.storm.hdfs.bolt.HdfsBolt"
        configMethods:
            -   name: "withFsUrl"
                args:
                    - "${bolt.hdfs.file.system.url}"
            -   name: "withFileNameFormat"
                args:
                    - ref: "filenameFormat"
            -   name: "withRecordFormat"
                args:
                    - ref: "recordFormat"
            -   name: "withRotationPolicy"
                args:
                    - ref: "rotationPolicy"
            -   name: "withSyncPolicy"
                args:
                    - ref: "syncPolicy"
            -   name: "addRotationAction"
                args:
                    - ref: "moveFileAction"

streams:
    -   name: "spout -> parser"
        from: "testingSpout"
        to: "parserBolt"
        grouping:
            type: SHUFFLE
    -   name: "parser -> hdfs"
        from: "parserBolt"
        to: "hdfsBolt"
        grouping:
            streamId: "message"
            type: SHUFFLE
