---
- name: Generate ssh key on master and stage on local
  hosts: ambari_master
  sudo: yes
  tasks:
    - include_vars: roles/ambari_common/vars/main.yml
    - include: roles/ambari_common/tasks/ssh_keygen.yml keygen_user="{{ ambari_user }}"
    - name: Downloading pub key to local
      fetch: src=~/.ssh/id_rsa.pub dest={{ local_tmp_keygen_file }} flat=yes

- hosts: all
  sudo: yes
  roles:
    - role: ambari_common

- hosts: ambari_master
  sudo: yes
  roles:
    - role: ambari_master

- hosts: hadoop_*
  sudo: yes
  roles:
    - role: ambari_slave

- hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - include_vars: roles/ambari_common/vars/main.yml
    - name: Deleting local temp file
      file:  path={{ local_tmp_keygen_file }} state=absent
