---
- name: Download fixbuf
  get_url:
    url: "http://tools.netsa.cert.org/releases/libfixbuf-{{fixbuf_version}}.tar.gz"
    dest: "/tmp/libfixbuf-{{fixbuf_version}}.tar.gz"

- name: Extract fixbuf tarball
  unarchive:
    src: "/tmp/libfixbuf-{{fixbuf_version}}.tar.gz"
    dest: /tmp
    copy: no
    creates: "/tmp/libfixbuf-{{fixbuf_version}}"

- name: Compile and Install fixbuf
  shell: "{{item}}"
  args:
    chdir: "/tmp/libfixbuf-{{fixbuf_version}}"
  with_items:
    - ./configure
    - make
    - make install
