---
- name: Install prerequisites
  yum: name={{ item }}
  with_items:
    - "@Development tools"
    - libpcap
    - libpcap-devel
    - pcre
    - pcre-devel
    - glib2-devel
    - zlib
    - zlib-devel

- include: fixbuf.yml

- include: yaf.yml

- name: Turn on promiscuous mode for {{ sniff_interface }}
  shell: "ip link set {{ sniff_interface }} promisc on"

- set_fact:
    yaf: /usr/local/bin/yaf
    yafscii: /usr/local/bin/yafscii
    yaf_log: /var/log/yaf.log
    yaf_lock: /var/lock/subsys/yaf
    kafka_prod: /usr/hdp/current/kafka-broker/bin/kafka-console-producer.sh

- name: Start yaf
  shell: "daemonize -c {{ yaf_home }} -e {{ yaf_log }} -o {{ yaf_log }} -l {{ yaf_lock }} {{ yaf }} --in {{ sniff_interface }} --live pcap | {{ yafscii }} --tabular | {{ kafka_prod }} --broker-list {{ kafka_broker_url }} --topic {{ yaf_topic }}"
  args:
    creates: "{{ yaf_lock }}"
