---
- name: Download yaf
  get_url:
    url: "http://tools.netsa.cert.org/releases/yaf-{{yaf_version}}.tar.gz"
    dest: "/tmp/yaf-{{yaf_version}}.tar.gz"

- name: Extract yaf tarball
  unarchive:
    src: "/tmp/yaf-{{yaf_version}}.tar.gz"
    dest: /tmp
    copy: no
    creates: /usr/local/bin/yaf

- name: Compile and install yaf
  shell: "{{item}}"
  args:
    chdir: "/tmp/yaf-{{yaf_version}}"
    creates: /usr/local/bin/yaf
  with_items:
    - ./configure --enable-applabel --enable-plugins
    - make
    - make install

- name: Create Yaf home directory
  file:
    path: "{{ yaf_home }}"
    state: directory
    mode: 0755

- name: Add Yaf startup script
  copy:
    src: start-yaf.sh
    dest: "{{ yaf_home }}/start-yaf.sh"
    mode: 0755
