---
# tasks file for ambari_config
- include: set_group_vars.yml 
  tags: 
    - create_cluster
    
- name: Create the ambari cluster
  ambari_cluster_state:
    host: "{{ ambari_host }}"
    port: "{{ ambari_port }}"
    username: "{{ ambari_user }}"
    password: "{{ ambari_password }}"
    cluster_name: "{{ cluster_name }}"
    cluster_state: present
    blueprint_name: "{{ blueprint_name }}"
    wait_for_complete: True
    blueprint_var: "{{ blueprint }}"
  tags: 
    - create_cluster

- name: Delete the ambari cluster
  ambari_cluster_state:
    host: "{{ ambari_host }}"
    port: "{{ ambari_port }}"
    username: "{{ ambari_user }}"
    password: "{{ ambari_password }}"
    cluster_name: "{{ cluster_name }}"
    cluster_state: absent
  tags: 
    - delete_cluster
