# Ambari agents register with the master using the fully qualified hostname
# of the agent machine. This captures the hostname of each agent machine 
# and populates a list variable to inject into the Blueprint variable
- name: get local FQDN of each master
  command: hostname -f
  register: master_output
  delegate_to: "{{item}}"
  with_items:
      - "{{groups.hadoop_master}}"
      
- name: get local FQDN of each slave
  command: hostname -f
  register: slave_output
  delegate_to: "{{item}}"
  with_items:
      - "{{groups.hadoop_slaves}}"
  
- set_fact: masters_group="{{ master_output.results | map(attribute='stdout') | list }}"
- set_fact: slaves_group="{{ slave_output.results | map(attribute='stdout') | list }}"
